services:
  - type: web
    name: neveroff
    env: python
    plan: free
    repo: https://github.com/X5-6/Z/
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    diskMounts:
      - diskName: neveroff-data
        path: /data
    envVars:
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
disks:
  - name: neveroff-data
    sizeGB: 1
